creation_rules:
  - path_regex: '\.env$'
    age: >-
      age1zptpgxhs9chnkudu69qut2hn706pmyngasvaz4ppf452un2x7p2ss6j96f,
      age15j0hsfgz0ru2ampfc7kt950gqzsfcgwejz2wctde0jeu8ky8k30qwmqwu0,
      age1ruyerr2ezjk636a0qexz8mnwx9u5azphpd55hs3l9ry5xr8wrvtszpgrkk,
      age10wglql3khh8jywavqpkkqvsa9gm7qv4rc2jdax0mp6cxjwu5c9msjwtznd


# 1. Elixpo Lap
# 2. 
# 3. Elixpo Desk
# 4. Elixpo Workstation
